version: "3.3"

services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432